### ISSUE TITLE
Remove spruious messages from the shorte log

### ISSUE THREAD

**Issue by bradfordelliott** [bradfordelliott/shorte#85]
Don't want to see this in the log file. An a -V option for verbose output.

```
Parsing include(s) [docs/sequences/ptp_sequences.tpl]
Image:
  src:  /cygdrive/c/usr/work/LEEDS/docs/images/ptp_flow_diagram.png
  name: ptp_flow_diagram
  ext:  .png
Image:
  src:  /cygdrive/c/usr/work/LEEDS/docs/images/ptp_timewheel_synchronization.png
  name: ptp_timewheel_synchronization
  ext:  .png
```
